/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
  }
}
